Strings fixed, non-strings made untranslatable
twireapp/Twire pull request #140
Opened 2020-10-07 19:04 UTC by comradekingu

2020-10-07 19:04 UTC, comradekingu commented on app/src/main/res/values/strings.xml
>      <string name="login_text_line_one">Let\'s get you set up!</string>
This should be a \n in the first sentence.

2020-10-09 18:13 UTC, samfundev commented
Looking over most of these changes I'm really confused what exactly is being fixed here. Could you go into a bit more detail about your reasons for these changes? I'm also confused about your comments:
> Not a fan of the BIGOPTIONS.

What are big options?
> This should be a \n in the first sentence.

Are you saying there should be a new line in the `login_text_line_one` string? And where exactly should it go?

Apologizes if I'm missing something here but I'm having trouble understanding this PR.

2020-10-09 22:36 UTC, comradekingu commented
@RickyM7 Yes, they can also be put in a different file, but making them untranslatable works. There are also some small fixes :)

2020-10-09 22:40 UTC, samfundev commented
@RickyM7 I agree that those should definitely be hidden but there are many other changes that I don't understand. It seems like all the uses of "fail" have been replaced by something else but I don't understand why you would want to do that.

2020-10-09 22:59 UTC, RickyM7 commented
@samfundev I didn’t replace it, I just replicated the base text, I did it exactly because I don’t know how to translate those texts, if I’m not mistaken there are more than 13 texts that I did that.

2020-10-09 23:05 UTC, samfundev commented
@RickyM7 Sorry if I was unclear but I'm not talking about strings in the screenshot you posted. I'm talking about the other changes that were made in this PR. Like this change: https://github.com/twireapp/Twire/pull/140/files#diff-01dafb3fd0217441330103cfc8300094L144-R144

2020-10-09 23:11 UTC, RickyM7 commented
@samfundev Sorry for the confusion.  Regarding these changes, I think @comradekingu wanted to reduce the length of the sentences, this must be what he meant by BIGOPTIONS, I think.

2020-10-09 23:25 UTC, comradekingu commented
@RickyM7 The big letter strings are ones like name="gen_dialog_login_or_out_logout_action">LOGOUT</string> and so on. Should be "Log Out" and similar.

2020-10-09 23:28 UTC, RickyM7 commented
@comradekingu I think it really looks better this way.

2020-10-10 03:24 UTC, comradekingu commented
@RickyM7 I thought you might. Right now the untranslatable strings are translatable, and that only causes trouble.

2020-10-10 03:54 UTC, RickyM7 commented
@comradekingu Sorry, I didn't quite understand what you meant.

2020-10-10 03:58 UTC, comradekingu commented
@RickyM7 All these are translatable https://hosted.weblate.org/zen/twire/strings/nb_NO/?q=check:same
They should not be, and my PR fixes that :)

2020-10-10 06:57 UTC, samfundev commented
@comradekingu I'd still like to know the reasons for the other changes. Currently I don't think see why these other changes should be merged in. And I'd really like to at least mark those strings as untranslated as soon as possible.

2020-10-10 07:03 UTC, comradekingu commented
@samfundev The other fixes are just grammar, consistency, and to make it seem a bit friendlier.

2020-10-10 09:10 UTC, RickyM7 commented
@comradekingu But you should leave the words "Login" and "Logout" like that instead of "Log in" and "Log out" as they separate the way you left it looks a little strange. But the rest of the changes are good, in addition to making the base language a little more polished, it also makes those who will translate the app more comfortable.

2020-10-10 17:12 UTC, samfundev requested changes
Noticed a few things with the new strings.

2020-10-10 17:12 UTC, samfundev commented on app/src/main/res/values/strings.xml
> +    <string name="led_activity_settings_notifications">Shine LED</string>
Shine doesn't work here because the app doesn't shine the LED, an LED shines. Light up makes the most sense to me but turn on or activate would work.

2020-10-10 17:12 UTC, samfundev commented on app/src/main/res/values/strings.xml
> +    <string name="changelog_show_after_update">Show changelog in new versions</string>
I feel like "in new versions" is a bit confusing. Like the changelog could show up multiple times in new versions. "for new versions" could work but is still a bit unclear. I feel like it's pretty clear already but you could change it to "after a new update" if you wanted to be even clearer.

2020-10-10 17:37 UTC, comradekingu commented on app/src/main/res/values/strings.xml
> +    <string name="chat_status_connection_failed">Connection Dropped</string>
Both could suggest it has already been established. Will change.

2020-10-10 17:43 UTC, comradekingu commented on app/src/main/res/values/strings.xml
> +    <string name="led_activity_settings_notifications">Shine LED</string>
Can use for both, but fair point.

2020-10-10 17:43 UTC, comradekingu commented on app/src/main/res/values/strings.xml
> +    <string name="led_activity_settings_notifications">Shine LED</string>
```suggestion
    <string name="led_activity_settings_notifications">Turn on LED</string>
```

2020-10-10 17:43 UTC, comradekingu commented on app/src/main/res/values/strings.xml
> +    <string name="changelog_show_after_update">Show changelog in new versions</string>
```suggestion
    <string name="changelog_show_after_update">Show new changelogs</string>
```

2020-10-10 17:47 UTC, comradekingu commented on app/src/main/res/values/strings.xml
> +    <string name="chat_status_connection_failed">Connection Dropped</string>
```suggestion
    <string name="chat_status_connection_failed">Could not connect</string>
```

2020-10-10 17:47 UTC, comradekingu commented on app/src/main/res/values/strings.xml
> +    <string name="led_activity_settings_notifications">Shine LED</string>
```suggestion
    <string name="led_activity_settings_notifications">Turn on LED</string>
```

2020-10-10 17:48 UTC, comradekingu commented on app/src/main/res/values/strings.xml
> +    <string name="changelog_show_after_update">Show changelog in new versions</string>
```suggestion
    <string name="changelog_show_after_update">Show a summary of changes for new versions</string>
```

2020-10-10 17:49 UTC, comradekingu commented on app/src/main/res/values/strings.xml
> +    <string name="changelog_show_after_update">Show changelog in new versions</string>
Still hinges on knowing what a changelog is, which is already present in the title.

2020-10-10 17:51 UTC, comradekingu commented on app/src/main/res/values/strings.xml
> +    <string name="screen_wake_activity_settings_notifications">Turn on screen</string>
I like "turn on" and "turn off" for things either turned on or off. Could also avoid translations ala https://hosted.weblate.org/translate/twire/strings/de/?checksum=ea299bca080218f3

2020-10-10 17:53 UTC, comradekingu commented on app/src/main/res/values/strings.xml
> +    <string name="chat_status_connection_failed">Could not connect</string>
```suggestion
    <string name="chat_status_connection_failed">Could not connect.</string>
```

2020-10-10 17:53 UTC, comradekingu commented on app/src/main/res/values/strings.xml
> +    <string name="error_external_playback_failed">Could not send URL to external player</string>
```suggestion
    <string name="error_external_playback_failed">Could not send URL to external player.</string>
```

2020-10-10 17:53 UTC, comradekingu commented on app/src/main/res/values/strings.xml
>      <string name="my_games__error_none_found">No games found</string>
```suggestion
    <string name="my_games__error_none_found">Could not find any games.</string>
```

2020-10-10 17:54 UTC, comradekingu commented on app/src/main/res/values/strings.xml
> +    <string name="enum_no_internet_message">Not connected to the Internet</string>
```suggestion
    <string name="enum_no_internet_message">Connect to the Internet first</string>
```

2020-10-10 18:18 UTC, samfundev commented on app/src/main/res/values/strings.xml
> +    <string name="changelog_show_after_update">Show changelog in new versions</string>
I really don't think we need to explain what a changelog is because the user is already looking at one. It's even titled "Changelog".

2020-10-10 18:21 UTC, samfundev commented on app/src/main/res/values/strings.xml
> +    <string name="chat_status_connection_failed">Connection Dropped</string>
"Could not connect" doesn't work either. That only works if it fails while trying to connect but doesn't work if the connection is lost after connecting. It needs to work for both since it's used in both situations in the app.

2020-10-10 18:31 UTC, samfundev commented on app/src/main/res/values/strings.xml
> +    <string name="chat_status_connection_failed">Connection Dropped</string>
Also if you're going for consistency, I'd much rather use "failed" as the consistent phrase then "could not". So if you want, you could just fix all the times "could not" has been use and replace them with "failed".

2020-10-10 19:16 UTC, comradekingu commented on app/src/main/res/values/strings.xml
> +    <string name="changelog_show_after_update">Show changelog in new versions</string>
I agree, which is why saying "changelog" twice in the very least isn't doing anything.

2020-10-10 19:18 UTC, comradekingu commented on app/src/main/res/values/strings.xml
> +    <string name="chat_status_connection_failed">Connection Dropped</string>
Only English has that level of duality though. I'll double up on it instead.

2020-10-10 19:18 UTC, comradekingu commented on app/src/main/res/values/strings.xml
> +    <string name="chat_status_connection_failed">Could not connect.</string>
```suggestion
    <string name="chat_status_connection_failed">Could not establish or maintain connection.</string>
```

2020-10-11 21:05 UTC, samfundev commented
@comradekingu Sorry, I'd really like to clarify something before we continue discussing the changes in this PR.

I've been feeling like while this PR does make the source text more descriptive, it also makes the English translation worse for the sake of being more descriptive. Changing the source text should only be about making the English translation better and not making it more descriptive. If you want strings to be more descriptive that can be done through adding explanations or screenshots to strings in Weblate. I don't know if there's a way to allow other users to add explanations/screenshots to Weblate but I would also be happy to add any if you make some. You can also ask me to add some if there's some specific ones you want more clarification about.

For example, "Connection Failed" is a good English translation. It doesn't tell you exactly what went wrong because that's not important. All that's important is that the user knows something has gone wrong with the connection. "Could not establish or maintain connection." is not what we want to say. It tells the user what might have went wrong with the connection by being vague and describing two different possible events leaving the user lost about which one actually happened.

Having said that, I'm going to be honest and say that I feel like most of the changes made in this PR are making strings "more descriptive but worse as a English translation". The ones I'd say that don't fit that are marking strings as untranslatable and fixing "login" to "log in" since it's being used as an verb and not a noun. If you want to modify the PR to be just those changes or to fix up these changes to address this issue that I've been talking about then I'd accept it. I really appreciate you trying to help out but as it currently is, I'm not going to accept this PR.

2020-10-11 22:04 UTC, RickyM7 commented
@samfundev Meddling a little, I agree with you, for example, if the phrase "Connection Failed" explains well what happened, why change the phrase and make it bigger? It really doesn’t make sense to change, after all the sentence fits very well in the context and explains what’s needed, in addition this sentence is very simple to be translated into other languages. I think that all sentences that have "Failed" should remain as in the original text. About "wakeup screen" I think it should stay "wakeup" and about "Light up LED" I think "Turn on" fits very well. "Show changelog after an update" should also remain as in the original text, and finally, I believe that "Login" and "Logout" should remain that way, as this is more common and I think it is more pleasant as well. About the rest of the phrases, I believe that the way proposed by @comr is great, but the original way is also good.
Note: I'm saying this as someone looking for a text that is consistent and simple to translate.

2020-10-12 00:23 UTC, samfundev commented
@RickyM7 I wanted to explain about the whole "login" vs. "log in" thing. The reason I thought it should be changed is because, according to Wikionary, [login](https://en.wiktionary.org/wiki/login) is a noun while [log in](https://en.wiktionary.org/wiki/log_in) is a verb. And in all the cases it's being used in Twire, I believe it's being used as a verb.

2020-10-12 01:02 UTC, RickyM7 commented
@samfundev I understand, it is good anyway and to translate I believe that there is not much difference.

2020-10-12 03:28 UTC, comradekingu commented on app/src/main/res/values/strings.xml
> -    <string name="enum_no_internet_message">You don\'t seem to have an internet connection</string>
("internet" with small i here)

2020-10-12 03:29 UTC, comradekingu commented on app/src/main/res/values/strings.xml
> -    <string name="channel_info_bio">This user is apparently very private about the stream…</string>
What does this mean?

2020-10-12 03:29 UTC, comradekingu commented on app/src/main/res/values/strings.xml
> +    <string name="vod_playback_failed">Could not play VOD. Try changing the quality.</string>
lowering?

2020-10-12 03:31 UTC, comradekingu commented on app/src/main/res/values/strings.xml
> -    <string name="confirm_text_line_two">We just need to get your follows from Twitch.</string>
("We" for no good reason here.)

2020-10-12 04:00 UTC, comradekingu commented
@samfundev It is either descriptive or vague, whereas it could fail at the former, either being _unable to connect_ or _unable to keep the established connection up_ is what you told me. It can be "Connection failed" sure. My preference is one string for each condition, but for both "Connection failed" is the better string. That leaves translations in jeopardy.
I can either add a comment in the source strings here, or you can add https://hosted.weblate.org/user/kingu/ as an admin on Weblate so I can do it there.

The strings marked untranslatable should be untanslatable, there is nothing but loss to gain from having them be translatable.

You got "login" vs "log in" right, only mixed.
<string name="login_user_cancel">You need to log in to use Twire, though…</string>
vs
<string name="login_unvalid_token_text_line_two">have to login again</string>
were both in the original. Now it is "log in" consistently. (Changelogs should be in fastlane though.)

Maybe you also meant those are the only advantages, but that isn't the case either. Pointed out some things now, and fixed others.

Starting with the correct case for strings is an obvious place to start for correctness, but I'll leave that up to stylistic choice.

@RickyM7 "Connection failed" is not easy to translate, and it will fail. Be that as it may, it is not a bad error, and it can be mitigated. "Sit tight!" is also difficult.
"Failed" throughout isn't good because it isn't friendly, and in many cases it is quirky.
<string name="stream_no_chromecast_quality_supported">Sorry, this stream doesn\'t support </string>
will fail in some languages.
"Wakeup screen" is a noun for precisely the same reason "login" is…
<string name="gen_start_page">Startup Page</string> noun
    <string name="title_activity_welcome">Twire setup</string> noun, etc.

2020-10-14 22:35 UTC, samfundev commented on app/src/main/res/values/strings.xml
> +    <string name="vod_playback_failed">Could not play VOD. Try changing the quality.</string>
Changing the quality could fix the issue, so it's fine to be "changing" instead of "lowering".

2020-10-14 22:37 UTC, samfundev commented on app/src/main/res/values/strings.xml
> -    <string name="confirm_text_line_two">We just need to get your follows from Twitch.</string>
"We" is being used as the royal we here. Which is fine but I think the change you made is good.

2020-10-14 22:44 UTC, samfundev commented on app/src/main/res/values/strings.xml
> -    <string name="channel_info_bio">This user is apparently very private about the stream…</string>
It looks like this is used as a fallback if we're unable to load a user's biography. I think this was something that was a part of Pocket Plays (the original app) but never got finished.

2020-10-14 22:45 UTC, samfundev commented
@comradekingu
> is what you get with "connection failed", because it takes some deductive reasoning rather than going with one assumption.

I think you missed the point that I was trying to make. All we need to tell the user is "the connection has stopped working". Why the connection isn't working is entirely irrelevant. Sorry if I wasn't being clear about that. I've also added an explanation for this string on Weblate.

2020-10-14 22:53 UTC, samfundev commented on app/src/main/res/values/strings.xml
> +    <string name="changelog_show_after_update">Show changelog in new versions</string>
That makes sense. I think "Show this after an update" would work then.

2020-10-14 23:07 UTC, samfundev commented on app/src/main/res/values/strings.xml
> -    <string name="enum_no_internet_message">You don\'t seem to have an internet connection</string>
Not capitalization the word internet is a common thing. https://en.wikipedia.org/wiki/Capitalization_of_Internet
> The spelling "internet" has become commonly used, as the word almost always refers to the global network; the generic sense of the word has become rare in non-technical writings. As a result, The Chicago Manual of Style and the Associated Press (AP) both revised their formerly capitalized stylization of the word to lowercase "internet" in 2016. The New York Times, which followed suit in adopting the lowercase style, noted that such a change is common practice when "newly coined or unfamiliar terms" become part of the lexicon.

2020-10-14 23:10 UTC, comradekingu commented on app/src/main/res/values/strings.xml
> -    <string name="channel_info_bio">This user is apparently very private about the stream…</string>
So it is a placeholder where the biography would have been?
Is there anything the user can do to get to see it?
Like "Gain follower status to get to see this biography" or however it works.

2020-10-14 23:15 UTC, comradekingu commented on app/src/main/res/values/strings.xml
> -    <string name="enum_no_internet_message">You don\'t seem to have an internet connection</string>
"Internet" is still the proper one though.
Sticking with the theme of avoiding errors in translations here, at best lowercase "internet" only applies to English. In English Unicode is still always "Unicode"(?), and the Chicago style manual is as credible as the AP is. They can't afford to hire spellcheckers, so lately they have changed suggestions based on that.

2020-10-14 23:15 UTC, comradekingu commented on app/src/main/res/values/strings.xml
> +    <string name="vod_playback_failed">Could not play VOD. Try changing the quality.</string>
OK :)

2020-10-14 23:17 UTC, comradekingu commented on app/src/main/res/values/strings.xml
> +    <string name="changelog_show_after_update">Show a summary of changes for new versions</string>
```suggestion
    <string name="changelog_show_after_update">Show a summary of changes after installing a new version</string>
```

2020-10-14 23:30 UTC, samfundev commented on app/src/main/res/values/strings.xml
> +    <string name="changelog_show_after_update">Show changelog in new versions</string>
"Show a summary of changes after installing a new version" is "more descriptive but a worse English translation". "a summary of changes" is a changelog (or what I was referring by "this" in my other suggestion). And I've already explained that the user would know what a changelog is.

2020-10-14 23:31 UTC, samfundev commented on app/src/main/res/values/strings.xml
> -    <string name="enum_no_internet_message">You don\'t seem to have an internet connection</string>
> at best lowercase "internet" only applies to English.
Again, it doesn't need to apply to anything else besides English. This is the English translation.

2020-10-14 23:33 UTC, samfundev commented on app/src/main/res/values/strings.xml
> -    <string name="channel_info_bio">This user is apparently very private about the stream…</string>
No, not that I'm aware of. I'll probably just remove this string so I don't think we need to worry about it.

2020-10-15 00:43 UTC, comradekingu commented on app/src/main/res/values/strings.xml
> -    <string name="enum_no_internet_message">You don\'t seem to have an internet connection</string>
So in keeping with English, lets not write Internet with a small i. The conventional way to do it is "Internet".

2020-10-15 00:47 UTC, comradekingu commented on app/src/main/res/values/strings.xml
> +    <string name="changelog_show_after_update">Show changelog in new versions</string>
On the assumption the user knows what a changelog is, no summary is needed. Explaining what it is, in a clear manner isn't worse, it is better. "this" and an "update" is less clear. In systems that distinguish between updates and upgrades, "update" isn't installing new versions.

2020-10-15 02:36 UTC, samfundev commented on app/src/main/res/values/strings.xml
> -    <string name="enum_no_internet_message">You don\'t seem to have an internet connection</string>
From what I can see from the Wikipedia article, internet is really only capitalized in technical documents. And we're not writing technical document, we're writing for regular Android users. If you really think that Internet is the right way to write it then you can change it but I'm pretty sure the common way to write it is internet.

2020-10-15 03:26 UTC, samfundev commented on app/src/main/res/values/strings.xml
> +    <string name="changelog_show_after_update">Show changelog in new versions</string>
I mean, I'd argue that there is no assumption. They're looking at something titled "Changelog". Also update is what's used by everything on Android. They're updates on the Google Play Store, F-Droid and even for updating Android itself. I still think that the original is the best one so far but if you really want to change it, then I guess we'll just have to agree to disagree.

2020-10-15 04:42 UTC, comradekingu commented on app/src/main/res/values/strings.xml
> +    <string name="changelog_show_after_update">Show changelog in new versions</string>
No part of being shown how either of those operates, or their basic function hinges on knowing what a changelog is.
Where it says "Changelog" in F-Droid you are directly browsing the changelog, not making a future decision.
Let me regroup here, the assumption is that "changelog" works the second time, when it can fail the first, and keep failing to make matters worse. "Update" is avoided, which also isn't as clear, not as correct, and moreover doesn't bring much clarity to the original premise; the user not knowing what a changelog is.
My point is easy to test. Find a representative group of users, ask "What is a changelog?", and get less than ideal results.

2020-10-15 04:44 UTC, comradekingu commented on app/src/main/res/values/strings.xml
> -    <string name="enum_no_internet_message">You don\'t seem to have an internet connection</string>
No, it is consistently used by organizations that matter and are central to its creation and continuation.
It is, judging by the article, more common in the UK to write "internet". Citation needed, but "internet" has no obvious upside, but clear downsides.

2020-10-16 18:37 UTC, samfundev commented
I'm sorry, but I'm going to close this PR. I really do appreciate you trying to help out here but I just can't keep discussing these changes. Throughout this discussion, I've had to explain myself multiple times and I've struggled to understand what you're trying to say. Which has lead to me feeling very angry and frustrated. I hope that I haven't let that out on you in any way but I don't think I can keep doing this emotionally. Not only that but I feel like this is just devolving into opinion about what's the better way to phrase something or what's the correct way to write something. Both of which we could go back and forth on forever. I feel bad closing someone's PR but hopefully you can understand where I'm coming from here.
Instead, I've gone back through the strings again with a fine tooth comb and fixed up all the problems I've spotted. Which has included removing a lot of old strings that aren't used anymore and making corrections for a few others. I've also added some explanations to Weblate about the strings we've discussing.

2020-10-16 18:37 UTC, closed without merging