Add online since (runtime) label to stream cards
twireapp/Twire pull request #211
Opened 2021-04-18 10:06 UTC by Nickwasused

This is fixing #36 

The changes have been tested on:

- Android Virtual Pixel XL, Android 11.0
- Xiaomi Redmi Note 7, Android 11.0
- Samsung Galaxy Tab SM-T510, Android 10

I have tested every Theme of the App.

Here is a Preview:
Images:
[![image](https://i.imgur.com/R8DARPd_d.webp?maxwidth=760&fidelity=grand)]
[![image](https://i.imgur.com/8zVgUxl_d.webp?maxwidth=760&fidelity=grand)]

Video:
[![youtube](https://img.youtube.com/vi/dhEKPG9DT9c/0.jpg)](https://www.youtube.com/watch?v=dhEKPG9DT9c)

2021-06-26 06:40 UTC, samfundev requested changes
Appreciate the PR! I found a few things to improve.

2021-06-26 06:40 UTC, samfundev commented on app/src/main/java/com/perflyst/twire/fragments/StreamFragment.java
> +                new CountDownTimer(999999999, 1000) {
Couldn't this code be called from progressRunnable? That runs once a second, which is frequent enough. This reverse CountDownTimer approach seems a bit janky.

2021-06-26 06:40 UTC, samfundev commented on app/src/main/java/com/perflyst/twire/fragments/StreamFragment.java
> +                        }
These if statements can be simplified:
```suggestion
                        mRuntime.setText(String.format("%-2s:%-2s:%-2s", hour, min, sec).replace(' ', '0'));
```

2021-06-26 06:40 UTC, samfundev commented on app/src/main/java/com/perflyst/twire/fragments/StreamFragment.java
> +                Log.d("Runtime String", args.getString(getString(R.string.stream_fragment_runtime)));
Unnecessary logging.

2021-06-26 06:40 UTC, samfundev commented on app/src/main/java/com/perflyst/twire/fragments/StreamFragment.java
> +                //mRuntime.setText(String.valueOf(args.getString(getString(R.string.stream_fragment_runtime))));
I don't think this comment needs to be included.

2021-06-26 10:14 UTC, Nickwasused commented on app/src/main/java/com/perflyst/twire/fragments/StreamFragment.java
> +                //mRuntime.setText(String.valueOf(args.getString(getString(R.string.stream_fragment_runtime))));
Removed in https://github.com/twireapp/Twire/pull/211/commits/a190dbdb595d0bf8fdd47432b615b0556ef30c70

2021-06-26 10:14 UTC, Nickwasused commented on app/src/main/java/com/perflyst/twire/fragments/StreamFragment.java
> +                Log.d("Runtime String", args.getString(getString(R.string.stream_fragment_runtime)));
Removed in https://github.com/twireapp/Twire/pull/211/commits/a190dbdb595d0bf8fdd47432b615b0556ef30c70

2021-06-26 10:15 UTC, Nickwasused commented on app/src/main/java/com/perflyst/twire/service/Settings.java
> +    public void setStreamRuntime(boolean showRuntime) {
Changed in https://github.com/twireapp/Twire/pull/211/commits/a190dbdb595d0bf8fdd47432b615b0556ef30c70

2021-06-26 10:15 UTC, Nickwasused commented on app/src/main/res/values/strings.xml
> +    <string name="stream_runtime"></string>
The String has been removed in https://github.com/twireapp/Twire/pull/211/commits/a190dbdb595d0bf8fdd47432b615b0556ef30c70

2021-06-26 10:15 UTC, Nickwasused commented on app/src/main/res/values/strings.xml
> +    <string name="player_show_runtime">Show the Stream Runtime</string>
Moved to correct location in https://github.com/twireapp/Twire/pull/211/commits/a190dbdb595d0bf8fdd47432b615b0556ef30c70

2021-06-26 11:33 UTC, Nickwasused commented on app/src/main/java/com/perflyst/twire/fragments/StreamFragment.java
> +                new CountDownTimer(999999999, 1000) {
I have added its own runnable that runs every second in https://github.com/twireapp/Twire/pull/211/commits/bafd1f03537c69aa5f7ba141d6d3d7a4fe953569

2021-06-26 11:35 UTC, Nickwasused commented on app/src/main/java/com/perflyst/twire/fragments/StreamFragment.java
> +                        }
I have added a cleaner way of calculating the Date in  therefore this is not needed anymore: https://github.com/twireapp/Twire/pull/211/commits/bafd1f03537c69aa5f7ba141d6d3d7a4fe953569

2021-06-29 00:38 UTC, samfundev approved these changes

2021-06-29 00:38 UTC, samfundev commented
Everything looks good, merging. Many thanks!

2021-06-29 00:38 UTC, merged