Add SSL connection to irc
twireapp/Twire pull request #226
Opened 2021-06-04 09:36 UTC by Nickwasused

# Twitch
Twitch Offers both an unencrypted connection and an encrypted connection to their IRC servers.
The unencrypted Connection is to Port 6667 and the encrypted is to Port 6697.
![](https://i.imgur.com/AGoJwAy.png)
(See more about that here: https://dev.twitch.tv/docs/irc/guide)

# Implementation
I have added a Settings option for Choosing the connection type.
![](https://i.imgur.com/Oxljklh.png)

# Other Stuff
The Chat Server Url has changed from "irc.twitch.tv" to "irc.chat.twitch.tv" as seen here: https://dev.twitch.tv/docs/irc/guide.

2021-06-04 18:59 UTC, samfundev requested changes
Thanks for this PR! I did notice a few things that could be cleaned up before merging this in.

2021-06-04 18:59 UTC, samfundev commented on app/src/main/res/values/strings.xml
> +    <string name="chat_enable_ssl">Enable Secure Connection</string>
This should go under the `Chat Settings` section and use sentence case like the other settings.

2021-06-04 18:59 UTC, samfundev commented on app/src/main/java/com/perflyst/twire/service/Settings.java
> +    private final String CHAT_ENABLE_SSL = "chatenablessl";
Can you make the capitalization consistent?
```suggestion
    private final String CHAT_ENABLE_SSL = "chatEnableSSL";
```

2021-06-04 18:59 UTC, samfundev commented on app/src/main/java/com/perflyst/twire/chat/ChatManager.java
> +            Log.d("is connected", String.valueOf(socket.isConnected()));
This and the next 2 logging lines (reader & Line) seem unnecessary, could you remove them if they're not needed?

2021-06-05 10:51 UTC, Nickwasused commented on app/src/main/java/com/perflyst/twire/chat/ChatManager.java
> +            Log.d("is connected", String.valueOf(socket.isConnected()));
They have been removed in: https://github.com/twireapp/Twire/pull/226/commits/66a79c8ef2c86c3ff78a35e108785bc89679f95a

2021-06-05 10:51 UTC, Nickwasused commented on app/src/main/java/com/perflyst/twire/service/Settings.java
> +    private final String CHAT_ENABLE_SSL = "chatenablessl";
Fixed in: https://github.com/twireapp/Twire/pull/226/commits/66a79c8ef2c86c3ff78a35e108785bc89679f95a

2021-06-05 10:53 UTC, Nickwasused commented on app/src/main/res/values/strings.xml
> +    <string name="chat_enable_ssl">Enable Secure Connection</string>
This has been changed in: https://github.com/twireapp/Twire/pull/226/commits/66a79c8ef2c86c3ff78a35e108785bc89679f95a

2021-06-09 20:16 UTC, samfundev approved these changes

2021-06-09 21:23 UTC, samfundev commented
Everything looks good now, I'll merge this in.

2021-06-09 21:23 UTC, merged