Add settings option for the player-type
twireapp/Twire pull request #228
Opened 2021-06-22 11:12 UTC by Nickwasused

This pull request adds a settings option for the Stream-Player-Type.

# Usecase:
- This can serve as Ad-Blocker
- Can be used to bypass possible problems in the future (e.g. if they disable the embed player, then users can swap directly without waiting for an update).

# There are differences between the player-types:
Player-Type | info
------------ | -------------
embed | has ads, all resolutions
site | has ads, all resolutions
thunderdome | has no ads, limited to 480p
picture-in-picture | has no ads, limited to 360p

2021-07-06 00:27 UTC, samfundev requested changes
Two minor things that could be improved.

2021-07-06 00:27 UTC, samfundev commented on app/src/main/java/com/perflyst/twire/activities/settings/SettingsStreamPlayerActivity.java
> +                    settings.setStreamPlayerType(which + 1);
Wouldn't it be easier to not increase this by 1? You're just going to subtract 1 later when you need to index into the types array.

2021-07-06 00:27 UTC, samfundev commented on app/src/main/java/com/perflyst/twire/fragments/StreamFragment.java
> +    private String[] types;
Is this private field ever used?

2021-07-06 10:29 UTC, Nickwasused commented on app/src/main/java/com/perflyst/twire/fragments/StreamFragment.java
> +    private String[] types;
removed in https://github.com/twireapp/Twire/pull/228/commits/8a1bfee6b4565fd7e133c3d498ddbb00b320ea3a

2021-07-06 10:31 UTC, Nickwasused commented on app/src/main/java/com/perflyst/twire/activities/settings/SettingsStreamPlayerActivity.java
> +                    settings.setStreamPlayerType(which + 1);
I think this is the simplest solution.

2021-07-20 15:44 UTC, samfundev commented on app/src/main/java/com/perflyst/twire/activities/settings/SettingsStreamPlayerActivity.java
> +                    settings.setStreamPlayerType(which + 1);
I don't see how it's simpler to add one and then immediately [remove one](https://github.com/twireapp/Twire/pull/228/files#diff-9b21c9fa2fb704b8990760ed90c86e1d868bb74e250e012dbff58858aa1204eeL1419). Removing the `+ 1` and `- 1` would be less code and give the same result. The only other thing you would need to be change the [default value for the setting](https://github.com/twireapp/Twire/pull/228/files#diff-cbae979bd7c74502cfaa84bd092213aaca32b1058faf4a0a5d603f74346be7c9R722) to be 0 instead of 1.

2021-07-20 16:27 UTC, Nickwasused commented on app/src/main/java/com/perflyst/twire/activities/settings/SettingsStreamPlayerActivity.java
> +                    settings.setStreamPlayerType(which + 1);
Last time I have overseen the calculation done in app/src/main/java/com/perflyst/twire/fragments/StreamFragment.java

It's working now without the weird +1 / -1 calculation.

Changed in: https://github.com/twireapp/Twire/pull/228/commits/08ba32a678ebe17465b1642e3e86052c9167c021

2021-07-21 14:18 UTC, samfundev approved these changes

2021-07-21 14:18 UTC, merged

2021-07-21 14:19 UTC, samfundev commented
Thanks for the PR! Really appreciate it.