Audio only
twireapp/Twire pull request #229
Opened 2021-06-25 11:44 UTC by Nickwasused

# Fix
This Pull request is fixing the Audio-only mode.
#44 

# The changes have been tested on:

- Android Virtual Foldable, Android 11.0

# Preview (with Sound)
[![youtube](https://img.youtube.com/vi/tS0fWhKZtZE/0.jpg)](https://www.youtube.com/watch?v=tS0fWhKZtZE)

2021-07-04 15:47 UTC, samfundev requested changes
Thanks for fixing up the audio-only mode! Found a few things to fix up.

2021-07-04 15:47 UTC, samfundev commented on app/src/main/java/com/perflyst/twire/fragments/StreamFragment.java
>          }
I think this can be simplified to:
```suggestion
        if (player != null) {
            player.pause();
        }
```

2021-07-04 15:47 UTC, samfundev commented on app/src/main/java/com/perflyst/twire/fragments/StreamFragment.java
> +
This trailing whitespace can be removed.

2021-07-04 15:47 UTC, samfundev commented on app/src/main/java/com/perflyst/twire/fragments/StreamFragment.java
> +
Extra blank line.

2021-07-04 15:47 UTC, samfundev commented on app/src/main/java/com/perflyst/twire/fragments/StreamFragment.java
> +
Since this PR is fixing audio-only, we should just remove this comment and code.

2021-07-04 15:47 UTC, samfundev commented on app/src/main/java/com/perflyst/twire/fragments/StreamFragment.java
> +        Log.d("Audio Only", String.valueOf(mAudioOnlySelector.isChecked()));
If these logging statements are unnecessary, could you remove them?

2021-07-04 16:11 UTC, Nickwasused commented on app/src/main/java/com/perflyst/twire/fragments/StreamFragment.java
>          }
Changed in https://github.com/twireapp/Twire/pull/229/commits/f1eeaa347d78c10662b394e8ac659fac59761445

2021-07-04 16:11 UTC, Nickwasused commented on app/src/main/java/com/perflyst/twire/fragments/StreamFragment.java
> +
Removed in https://github.com/twireapp/Twire/pull/229/commits/f1eeaa347d78c10662b394e8ac659fac59761445

2021-07-04 16:11 UTC, Nickwasused commented on app/src/main/java/com/perflyst/twire/fragments/StreamFragment.java
> +
Removed in https://github.com/twireapp/Twire/pull/229/commits/f1eeaa347d78c10662b394e8ac659fac59761445

2021-07-04 16:11 UTC, Nickwasused commented on app/src/main/java/com/perflyst/twire/fragments/StreamFragment.java
> +        Log.d("Audio Only", String.valueOf(mAudioOnlySelector.isChecked()));
Removed in https://github.com/twireapp/Twire/pull/229/commits/f1eeaa347d78c10662b394e8ac659fac59761445

2021-07-04 16:14 UTC, Nickwasused commented on app/src/main/java/com/perflyst/twire/fragments/StreamFragment.java
> +
Changed in https://github.com/twireapp/Twire/pull/229/commits/9a4dbdb33da51c5fae4c361fc05e5440c831abe6

2021-07-04 16:16 UTC, Nickwasused commented
I have updated the code according to the requested changes. Everything should be good now.

2021-07-06 00:28 UTC, samfundev approved these changes

2021-07-06 00:28 UTC, samfundev commented
LGTM, thanks for the PR!

2021-07-06 00:28 UTC, merged