add 7TV Emotes (https://7tv.app/)
twireapp/Twire pull request #232
Opened 2021-07-01 10:17 UTC by Nickwasused

7TV is an alternative to BTTV. 
Their Code is Open Source and can be found here: https://github.com/SevenTV
Their Website can be found here: https://7tv.app/
Privacy Policy of 7TV: https://7tv.app/legal/privacy

### Preview
[![](https://img.youtube.com/vi/CvjD5yX0eBU/0.jpg)](https://www.youtube.com/watch?v=CvjD5yX0eBU)

2021-12-09 14:09 UTC, Nickwasused commented
I have added Settings for all three Emote Services (BetterTTV, FFZ and 7TV). BTTV and FFZ are enabled by default like before and 7TV is opt-in.

2021-12-11 16:40 UTC, samfundev requested changes
Noticed a few things that could be improved.

2021-12-11 16:40 UTC, samfundev commented on app/src/main/java/com/perflyst/twire/chat/ChatEmoteManager.java
> +                emote.setCustomChannelEmote(true);
This shouldn't be set to true, it's a global emote.
```suggestion
```

2021-12-11 16:40 UTC, samfundev commented on app/src/main/java/com/perflyst/twire/chat/ChatManager.java
> +        }
I feel like using a JSONObject for this causes more hassle than just creating a quick class to store these three variables.

2021-12-11 16:40 UTC, samfundev commented on app/src/main/java/com/perflyst/twire/chat/ChatManager.java
> +        Log.d(LOG_TAG, "Chat Emote Settings: " + settings_object.toString());
If this debug statement is not useful to keep around, be sure to remove it.

2021-12-11 17:01 UTC, Nickwasused commented on app/src/main/java/com/perflyst/twire/chat/ChatManager.java
> +        Log.d(LOG_TAG, "Chat Emote Settings: " + settings_object.toString());
removed in b2b8021e45554adfca7278d49cef05ababaa026d

2021-12-11 17:02 UTC, Nickwasused commented on app/src/main/java/com/perflyst/twire/chat/ChatEmoteManager.java
> +                emote.setCustomChannelEmote(true);
set to false in b2b8021e45554adfca7278d49cef05ababaa026d

2021-12-11 17:03 UTC, Nickwasused commented on app/src/main/java/com/perflyst/twire/chat/ChatManager.java
> +        }
I have added the Class "ChatEmoteSettings" in b2b8021e45554adfca7278d49cef05ababaa026d.

2021-12-12 04:16 UTC, samfundev requested changes
Apologizes, but I realized there is an even easier solution that would simplify the code.

2021-12-12 04:16 UTC, samfundev commented on app/src/main/java/com/perflyst/twire/chat/ChatEmoteManager.java
> +    ChatEmoteManager(String channelName, int channelId, ChatEmoteSettings emotesettings) {
Sorry, after reviewing this again I realized that there is an even easier solution. Just pass the settings along from the ChatManager.
```suggestion
    ChatEmoteManager(String channelName, int channelId, Settings settings) {
```

2021-12-12 10:37 UTC, Nickwasused commented on app/src/main/java/com/perflyst/twire/chat/ChatEmoteManager.java
> +    ChatEmoteManager(String channelName, int channelId, ChatEmoteSettings emotesettings) {
Done in 9ac85cef6e545d9bc5ea01b033c01d6ca5fa9375

2021-12-14 10:57 UTC, merged