Add offline follows
twireapp/Twire pull request #240
Opened 2021-08-07 13:51 UTC by Nickwasused

# How this works
With Account:
- Your Follows get imported from Twitch
- You can´t unfollow someone that you followed on Twitch
- You can follow new Channels from within the App
- You can unfollow the Channels that you followed in the App
- Follows from within the App are not synced (because #230)

Without Account:
- You can follow new Channels from within the App
- You can unfollow the Channels that you followed in the App
- Your Channels get shown in the My Streams Tab when they are live

# Showcase

## With Account
[![youtube](https://img.youtube.com/vi/MXUcvombeBc/0.jpg)](https://www.youtube.com/watch?v=MXUcvombeBc)
- Ubisoft and Bobross are Channels that got imported from Twitch

## Without Account
[![youtube](https://img.youtube.com/vi/0gz5XRPARWA/0.jpg)](https://www.youtube.com/watch?v=0gz5XRPARWA)
- Bob Ross is used as Showcase Channel

# Fixing
This should be closing:
#239 
#230
(Maybee #81 and #124)

2021-08-07 15:27 UTC, RickyM7 commented
This is amazing. A question, will an option be added to export/import the list of followed channels?

2021-08-12 07:23 UTC, Nickwasused commented
I have added basic export/import functions in https://github.com/twireapp/Twire/pull/240/commits/acc3ac7451ddbc23403481bcdfc0e72e3be126a8

The follows get exported to the Twire data folder.

2021-08-12 10:31 UTC, RickyM7 commented
> I have added basic export/import functions in acc3ac7
> 
> The follows get exported/imported to/from the Twire data folder.

I just tested it. Export works normally, but import doesn't work and the app even crashes sometimes when using this option.

2021-08-12 12:05 UTC, RickyM7 commented
The error continues (I tested the last apk generated). I also have a suggestion, is there a way to make a popup message appear whenever we export/import channels?

``
time: 1628769584734
msg: java.lang.AssertionError: Could not execute method for android:onClick
stacktrace: java.lang.IllegalStateException: Could not execute method for android:onClick
	at android.view.View$DeclaredOnClickListener.onClick(View.java:6268)
	at android.view.View.performClick(View.java:7448)
	at com.balysv.materialripple.MaterialRippleLayout$PerformClickEvent.run(MaterialRippleLayout.java:648)
	at com.balysv.materialripple.MaterialRippleLayout.onTouchEvent(MaterialRippleLayout.java:227)
	at android.view.View.dispatchTouchEvent(View.java:14309)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3112)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2785)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:488)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1873)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4125)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:446)
	at android.view.View.dispatchPointerEvent(View.java:14568)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6027)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5825)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5316)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5373)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5339)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5491)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5347)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5548)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5320)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5373)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5339)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5347)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5320)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8091)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8042)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8003)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8214)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:183)
	at android.app.ActivityThread.main(ActivityThread.java:7665)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at android.view.View$DeclaredOnClickListener.onClick(View.java:6263)
	... 54 more
Caused by: java.lang.AssertionError
	at com.perflyst.twire.service.SubscriptionsDbHelper.onImport(SubscriptionsDbHelper.java:116)
	at com.perflyst.twire.activities.settings.SettingsGeneralActivity.onImport(SettingsGeneralActivity.java:168)
	... 56 more
``

2021-08-12 16:58 UTC, RickyM7 commented
Tested f2f24d8 artifact. The Import option still doesn't work.

``
time: 1628787268123
msg: java.lang.AssertionError
stacktrace: java.lang.AssertionError
	at com.perflyst.twire.service.SubscriptionsDbHelper.onImport(SubscriptionsDbHelper.java:134)
	at com.perflyst.twire.activities.settings.SettingsGeneralActivity.lambda$onImport$7$SettingsGeneralActivity(SettingsGeneralActivity.java:191)
	at com.perflyst.twire.activities.settings.-$$Lambda$SettingsGeneralActivity$8UY9iNiS7RYCzRPXobFxZ1XwcPs.onClick(Unknown Source:2)
	at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:343)
	at android.view.View.performClick(View.java:7448)
	at android.view.View.performClickInternal(View.java:7425)
	at android.view.View.access$3600(View.java:810)
	at android.view.View$PerformClick.run(View.java:28305)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7665)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
``

2021-12-16 20:45 UTC, samfundev requested changes
I haven't checked through everything, but I'm going to stop my review for now so that these initial comments can be worked on.

2021-12-16 20:45 UTC, samfundev commented on app/src/main/java/com/perflyst/twire/tasks/GetStreamsCountTask.java
> +            String kraken_url = "https://api.twitch.tv/kraken/streams?limit=100&stream_type=live&offset=0&channel=";
This should probably be moved to the [new Helix API](https://dev.twitch.tv/docs/api/reference#get-streams) and add support for pagination so the count doesn't stop at 100.

2021-12-16 20:45 UTC, samfundev commented on app/src/main/java/com/perflyst/twire/misc/FollowHandler.java
> +        return isStreamerTwitch;
```suggestion
        isStreamerFollowed = Service.isUserFollowingStreamer(mChannelInfo.getStreamerName(), mContext);
        return isStreamerFollowed;
    }
    public boolean isStreamerTwitch() {
        isStreamerTwitch = Service.isUserTwitch(mChannelInfo.getUserId(), mContext);
        return isStreamerTwitch;
```

2021-12-16 20:45 UTC, samfundev commented on app/src/main/java/com/perflyst/twire/misc/FollowHandler.java
>          } else {
Why not invert the condition?

2021-12-16 20:45 UTC, samfundev commented on app/src/main/java/com/perflyst/twire/misc/FollowHandler.java
> +            }
```suggestion
            if (isUserFollowed) {
                isStreamerFollowed = true;
            }
            isStreamerTwitch = Service.isUserTwitch(mChannelInfo.getUserId(), mContext);
```

2021-12-16 20:45 UTC, samfundev commented on app/src/main/java/com/perflyst/twire/activities/settings/SettingsGeneralActivity.java
> +            Toast infoToast = Toast.makeText(getBaseContext(),"Exported " + exported + " Follows", Toast.LENGTH_SHORT);
This string is not localized.

2021-12-16 20:45 UTC, samfundev commented on app/src/main/java/com/perflyst/twire/activities/settings/SettingsGeneralActivity.java
> +            Toast infoToast = Toast.makeText(getBaseContext(),"Imported " + imported + " Follows", Toast.LENGTH_SHORT);
This string is not localized.

2021-12-16 20:45 UTC, samfundev commented on app/src/main/java/com/perflyst/twire/activities/settings/SettingsGeneralActivity.java
> +            Toast infoToast = Toast.makeText(getBaseContext(),"Wiped Follows", Toast.LENGTH_SHORT);
This string is not localized.

2021-12-16 20:45 UTC, samfundev commented on app/src/main/java/com/perflyst/twire/activities/ChannelActivity.java
> +        if (mFollowHandler.isStreamerFollowed() && mFollowHandler.isStreamerTwitch()) {
Why does this check if the streamer is followed? Couldn't we just check if the follow is from Twitch?

2021-12-16 20:45 UTC, samfundev commented on app/src/main/java/com/perflyst/twire/activities/ChannelActivity.java
> +                    }
Why are we checking if the streamer is from Twitch? And if they are we're hiding the button, even though it's already hidden by line 309?

2021-12-17 10:46 UTC, Nickwasused commented on app/src/main/java/com/perflyst/twire/fragments/NavigationDrawerFragment.java
> +         */
Removed in e33e590f68a088e41086760ac775bbd4eb139984

2021-12-17 10:52 UTC, Nickwasused commented on app/src/main/res/values/strings.xml
> +    <string name="gen_import_database">Import Follows</string>
Changed in f45b1f1c7f2c0da7213d08525d1366fa8d00bc4a

2021-12-17 11:12 UTC, Nickwasused commented on app/src/main/java/com/perflyst/twire/activities/settings/SettingsGeneralActivity.java
> +            Toast infoToast = Toast.makeText(getBaseContext(),"Exported " + exported + " Follows", Toast.LENGTH_SHORT);
Changed in 16694b36622fa1e6aaf50eff17ee1ea7c8d6c090

2021-12-17 11:12 UTC, Nickwasused commented on app/src/main/java/com/perflyst/twire/activities/settings/SettingsGeneralActivity.java
> +            Toast infoToast = Toast.makeText(getBaseContext(),"Wiped Follows", Toast.LENGTH_SHORT);
Changed in 16694b36622fa1e6aaf50eff17ee1ea7c8d6c090

2021-12-17 11:12 UTC, Nickwasused commented on app/src/main/java/com/perflyst/twire/activities/settings/SettingsGeneralActivity.java
> +            Toast infoToast = Toast.makeText(getBaseContext(),"Imported " + imported + " Follows", Toast.LENGTH_SHORT);
Changed in 16694b36622fa1e6aaf50eff17ee1ea7c8d6c090

2021-12-17 11:18 UTC, Nickwasused commented on app/src/main/java/com/perflyst/twire/activities/ChannelActivity.java
> +        if (mFollowHandler.isStreamerFollowed() && mFollowHandler.isStreamerTwitch()) {
Changed in df0f06c1b0229e65d28da947cc3db8443033bfee

2021-12-17 11:19 UTC, Nickwasused commented on app/src/main/java/com/perflyst/twire/activities/ChannelActivity.java
> +                    }
Duplicate check removed in df0f06c1b0229e65d28da947cc3db8443033bfee

2021-12-17 11:27 UTC, Nickwasused commented on app/src/main/java/com/perflyst/twire/misc/FollowHandler.java
> +        return isStreamerTwitch;
Changed in 96e422e91645f6ec8afb3565efd90a543bc9e742

2021-12-17 11:28 UTC, Nickwasused commented on app/src/main/java/com/perflyst/twire/misc/FollowHandler.java
> +            }
Changed in 96e422e91645f6ec8afb3565efd90a543bc9e742

2021-12-17 11:28 UTC, Nickwasused commented on app/src/main/java/com/perflyst/twire/misc/FollowHandler.java
>          } else {
Inverted in 96e422e91645f6ec8afb3565efd90a543bc9e742

2021-12-17 14:45 UTC, Nickwasused commented on app/src/main/java/com/perflyst/twire/tasks/GetStreamsCountTask.java
> +            String kraken_url = "https://api.twitch.tv/kraken/streams?limit=100&stream_type=live&offset=0&channel=";
I have changed the API to Helix and support for more than 100 Channel in 3a1684851a9ccf94757efdb861886fb0d354fe9e

2022-01-01 20:14 UTC, samfundev requested changes
Noticed a few more things.

2022-01-01 20:14 UTC, samfundev commented on app/src/main/java/com/perflyst/twire/activities/main/MyStreamsActivity.java
> +        String kraken_url = "https://api.twitch.tv/kraken/streams?limit=" + getLimit() + "&stream_type=live&offset=" + getCurrentOffset()+ "&channel=";
This should also be moved to the helix API.

2022-01-01 20:14 UTC, samfundev commented on app/src/main/java/com/perflyst/twire/service/SubscriptionsDbHelper.java
> +                // TO-DO Save File
This TODO seems like it's completed.

2022-01-03 09:51 UTC, Nickwasused commented on app/src/main/res/values/strings.xml
> +    <string name="gen_dialog_follows_cancel_action">Cancel</string>
Changed in c054689cca0ff21294051ecd00c5ef5eb52586d6

2022-01-03 09:52 UTC, Nickwasused commented on app/src/main/res/layout/activity_settings_general.xml
> +                android:background="?attr/dividerColor" />
No, removed in f0cedc3d0803a96a154a4a8f57ddf29599dc1ba4

2022-01-03 09:53 UTC, Nickwasused commented on app/src/main/java/com/perflyst/twire/service/SubscriptionsDbHelper.java
> +                // TO-DO Save File
Removed in eba321f25a61ac172f27085cbbb03c8bc78f6632

2022-01-03 13:23 UTC, Nickwasused commented on app/src/main/java/com/perflyst/twire/activities/main/MyStreamsActivity.java
> +        String kraken_url = "https://api.twitch.tv/kraken/streams?limit=" + getLimit() + "&stream_type=live&offset=" + getCurrentOffset()+ "&channel=";
Helix is added in 8bef94a0772d842ff4c2a265077a7185794122a6, 995bb9dd172294a895fefa34fd02f4f5f6ebba23 and ce98da971618bc54a322f84b516ba9f66dbb337b

2022-02-14 17:27 UTC, samfundev commented
@Nickwasused Should I continue reviewing this or are you still working on it? Some stuff is still unresolved from the previous review.

2022-02-15 10:03 UTC, Nickwasused commented on app/src/main/java/com/perflyst/twire/activities/main/MyChannelsActivity.java
> +        This is not updating, for the moment we are going to force reload it every time
Well I don´t exactly remember what i meant with that, but it got reverted in 36fcec83311ff556e1c8bf578622271cfe6e4c22

2022-02-15 10:11 UTC, Nickwasused commented on app/src/main/java/com/perflyst/twire/activities/settings/SettingsGeneralActivity.java
> +        dialog.show();
Changed in 0729d3fbffc0ba8ed77461fe070e005d9f521652

2022-02-15 10:33 UTC, Nickwasused commented
@samfundev I think you can start to review, the only thing left is to move the search to helix.

2022-02-15 18:23 UTC, samfundev requested changes
Hopefully the last review.

2022-02-15 18:23 UTC, samfundev commented on app/src/main/java/com/perflyst/twire/activities/main/MyStreamsActivity.java
>          List<StreamInfo> mResultList = new ArrayList<>();
Guava has a really nice method that makes this much simplier.
```suggestion
        String helix_url = "https://api.twitch.tv/helix/streams?first=100";

        ArrayList<ChannelInfo> channels;
        if (TempStorage.hasLoadedStreamers()) {
            channels = new ArrayList<>(TempStorage.getLoadedStreamers());
        } else {
            GetFollowsFromDB subscriptionsTask = new GetFollowsFromDB();
            subscriptionsTask.executeOnExecutor(AsyncTask.THREAD_POOL_EXECUTOR, getBaseContext());
            channels = new ArrayList<>(subscriptionsTask.get().values());
        }

        // loop over all channel in the DB in chunks of 100
        List<StreamInfo> mResultList = new ArrayList<>();
        final String ARRAY_KEY = "data";
        for (List<ChannelInfo> chunk : Lists.partition(channels, 100)) {
            String url = helix_url + Lists.transform(chunk, channelInfo -> "&user_id=" + channelInfo.getUserId());

            // request the url
            String temp_jsonString = Service.urlToJSONStringHelix(url, this);
            JSONObject fullDataObject = new JSONObject(temp_jsonString);
            // create the array
            JSONArray temp_array = fullDataObject.getJSONArray(ARRAY_KEY);
            // append the new array to the final one
            for (int i = 0; i < temp_array.length(); i++) {
                JSONObject streamObject = temp_array.getJSONObject(i);
                mResultList.add(JSONService.getStreamInfo(getBaseContext(), streamObject, null, false));
            }
        }
```

2022-02-15 18:23 UTC, samfundev commented on app/src/main/java/com/perflyst/twire/activities/main/MyStreamsActivity.java
This is covered by the other suggestion and can be deleted. (For some reason, I can't just make this one suggestion)
```suggestion
```

2022-02-16 14:47 UTC, Nickwasused commented on app/src/main/java/com/perflyst/twire/service/JSONService.java
> +    public static int getVodlenght(String length) {
Changed in 43230f31ada33ab919dcfc9d5634d215e85488c5

2022-02-16 14:54 UTC, Nickwasused commented on app/src/main/java/com/perflyst/twire/activities/main/MyChannelsActivity.java
> +            return new ArrayList<>(subscriptionsTask.get().values());
Changed back in 2b537088036a1eccbf901b5fc0684c5470854bf8

2022-02-16 15:33 UTC, Nickwasused commented on app/src/main/java/com/perflyst/twire/activities/main/MyStreamsActivity.java
Done in e7dc3eddc07ef5f0e0b5710432a050e6010be40e

2022-02-16 16:12 UTC, samfundev commented on app/src/main/java/com/perflyst/twire/activities/main/MyStreamsActivity.java
> +            String url = helix_url + id_string;
Oh sorry about that, there is a easy way to make the list into a string. I forgot to use that in my suggestion.
```suggestion
            String url = helix_url + Joiner.on("").join(Lists.transform(chunk, channelInfo -> "&user_id=" + channelInfo.getUserId()));
```

2022-02-16 16:40 UTC, Nickwasused commented on app/src/main/java/com/perflyst/twire/activities/main/MyStreamsActivity.java
> +            String url = helix_url + id_string;
Thanks! Changed in c500ea5546059102be290b92bcced70a51ca3a90

2022-02-16 17:02 UTC, merged

2022-02-16 17:07 UTC, samfundev commented
@Nickwasused Oh wait, are you going to migrate the search to helix as well?

2022-02-16 17:15 UTC, Nickwasused commented
@samfundev It would be great if you can take a look at it.