Emote fixes and improvements
twireapp/Twire pull request #258
Opened 2021-10-29 21:19 UTC by samfundev

While I was working on fixing #245, I ran into some other issues with emotes and so I've fixed up those as well. I've put each change into a separate commit so it should be easier to review.

What's been changed:
 - I refactored IRC message parsing because it wasn't easy to add new features and used a bunch of different regexes.
 - Emote IDs have changed so the regex needed to be changed to match them.
 - I used the method described [here](https://discuss.dev.twitch.tv/t/announcing-api-endpoints-for-twitch-emotes/32073/22) to get the emotes available to the user.
 - The emote menu was really stuttery, so I did some performance testing and found two performance improvements that made it much smoother. I also added support for Twitch's native animated emotes.
 
This PR replaces #251.

2021-10-30 08:45 UTC, Nickwasused requested changes
The only Issue I encountered is that the Badges would crash the App. But the emotes were working both sent from me and other Users. The performance of the emote keyboard is not great but it's definitely useable.

2021-10-30 08:45 UTC, Nickwasused commented on app/src/main/java/com/perflyst/twire/chat/ChatManager.java
> +        if (!badgeString.isEmpty()) {
This maybee should be `if (badgeString != null && !badgeString.isEmpty()) {` because otherwiese the App will hard crash when joining a Stream.

2021-10-30 17:07 UTC, samfundev commented on app/src/main/java/com/perflyst/twire/chat/ChatManager.java
> +        if (!badgeString.isEmpty()) {
Gotcha, I've changed it to check for the null.

2021-11-02 06:27 UTC, Nickwasused approved these changes

2021-11-02 14:03 UTC, merged