Fix crash when chat roomstate changes
twireapp/Twire pull request #280
Opened 2021-12-11 14:52 UTC by t0pu

Only changed roomstate will be contained in the `ROOMSTATE` message when the state is changed while already connected to chat. This causes a `NullPointerException` in `handleRoomstate()` resulting in a crash.

This fix checks if the three supported roomstates exist in the message first, before reading their value. This also properly ignores "unsupported" roomstates like `emote-only`.

I also found that if only `r9k` and `subs-only` was enabled, the chat stausbar would only show the r9k-icon. That's why I added the anchor element. I don't know if this is the right way to do it, but it fixed the issue.

2021-12-16 21:25 UTC, samfundev requested changes
Thanks for the PR! After looking over the code, I think there are some ways the code could be improved even further.

2021-12-16 21:25 UTC, samfundev commented on app/src/main/java/com/perflyst/twire/chat/ChatManager.java
>          }
After looking at the [documentation](https://dev.twitch.tv/docs/irc/tags#roomstate-twitch-tags), I realized that the roomstate is only sent on joining or with a change. So we don't need to check to see if the roomstate has changed.
```suggestion
        if (message.tags.get("r9k") != null) {
            chatIsR9kmode = message.tags.get("r9k").equals("1");
        }
        if (message.tags.get("slow") != null) {
            chatIsSlowmode = !message.tags.get("slow").equals("0");
        }
        if (message.tags.get("subs-only") != null) {
            chatIsSubsonlymode = message.tags.get("subs-only").equals("1");
        }

        onProgressUpdate(new ProgressUpdate(ProgressUpdate.UpdateType.ON_ROOMSTATE_CHANGE));
```

2021-12-16 21:25 UTC, samfundev commented on app/src/main/res/layout/fragment_chat.xml
> +
Adding this anchor is probably not the best solution. I think the proper fix would be changing from using a RelativeLayout as a parent to using a LinearLayout.

2021-12-18 12:59 UTC, t0pu commented on app/src/main/java/com/perflyst/twire/chat/ChatManager.java
>          }
I think the check is still necessary because the roomstate still can be changed to one that won't affect the icons in the statusbar. Those states would be `emote-only` and `followers-only`. Changing in and out of emote-only-mode can be quite common, as this was the reason why I noticed the crash in the first place. Unnecessarily firing the `ON_ROOMSTATE_CHANGE` event certainly won't break anything but it isn't pretty either.

2021-12-18 13:03 UTC, t0pu commented on app/src/main/res/layout/fragment_chat.xml
> +
I added a commit with the changes to a LinearLayout. It also fixes the issue of the icons not showing correctly. This might be the cleaner solution.

2021-12-18 22:20 UTC, samfundev approved these changes

2021-12-18 22:20 UTC, merged